### ISSUE TITLE
Add an allocator with MPK support

### ISSUE THREAD

**Issue by endbr64** [immunant/IA2-Phase2#134]
Our current plan is to leave `ngx_alloc()` and `ngx_calloc()` unwrapped to read the PKRU of the caller and allocate on the corresponding heap. We also still need to choose an allocator.

**Comment by ayrtonm** [comment]
I switched our approach for replacing the allocator (#145) from symbol overriding to ld --wrap because it gives us more precise control over which shared libraries will use partition alloc and which use the default malloc implementation.

PR #164 adds support for protecting heap memory, but it only handles memory reserved for allocations and does not protect any [allocator metadata](https://chromium.googlesource.com/chromium/src/+/master/base/allocator/partition_allocator/PartitionAlloc.md#architecture). Looking into what metadata needs to be protected is probably higher priority than the missing items in the previous comment.

**Comment by ayrtonm** [comment]
I fixed the issue [Stephen pointed out](https://github.com/immunant/IA2-Phase2/pull/164#discussion_r967559165) with shared allocations in #164. Ideally we'd use partition alloc for both shared and private allocations, but that requires a decent number of changes to PA and it's less important than the allocator metadata issue (#165). PRs #145 and #164 are ready to merge as soon as I add a few more tests and throw together an update script (or just copy my .bash_history) for updating the chromium sources.

**Comment by fw-immunant** [comment]
Unassigned as I'm not working on this at present, and I think @endbr64 is closer as that's who did most of the PartitionAlloc work.

**Comment by rinon** [comment]
Nginx with partition-alloc is working and landed
