### ISSUE TITLE
Switch to main compartment (if any) before `main()` runs

### ISSUE THREAD

**Issue by rinon** [immunant/IA2-Phase2#171]
We currently leave the PKRU state in the default state initialized by libc. We should switch to the proper compartment (if any) before `main` runs.

**Comment by fw-immunant** [comment]
I spent some time looking into this recently. One problem: our interface for compartmentalized programs doesn't give a good way for IA2 to know the compartment ID of the compartment that provides `main`.

Our current interface consists of the main compartment calling `INIT_RUNTIME(NUMBER_OF_COMPARTMENTS);` and `INIT_COMPARTMENT(MAIN_COMPARTMENT_ID);`, and other compartments doing `INIT_COMPARTMENT(OWN_COMPARTMENT_ID);`. The `INIT_RUNTIME` macro knows it is called in the main compartment, but doesn't know the ID of the main compartment. Meanwhile, the `INIT_COMPARTMENT` macro knows the compartment ID but not whether that compartment provides `main`.

In our tests so far, the main compartment always happens to be compartment 1, with libraries used being either compartment 0 (which does not require a corresponding call to `INIT_COMPARTMENT` or compartment 2 (which does call `INIT_COMPARTMENT(2)`). However, I don't think there's any reason that the two-compartment case must give compartment 1 to the compartment exposing the `main` function and compartment 2 to libraries, rather than vice-versa, or some other scheme. Arguably we should test the flipped case, at least.

Do we want to mandate a numbering scheme, provide some way to specify which compartment provides main, or do something else? What about if the main compartment is untrusted? (Do we support that?)

**Comment by fw-immunant** [comment]
For now we just assume compartment 1 contains `1main`.
